### ISSUE TITLE
Objeto valor cita

### ISSUE THREAD

**Issue by argelion14** [Antobio17/IV#16]
En relación al issue #7 voy a abordar el problema desarrollando el objeto valor cita que almacenará los tipos de cita deseados así como un identificador del cliente

**Comment by Antobio17** [comment]
Como bien indicas en el título del issue _cita_ sería una entidad no un objeto valor como se dice en el comentario.
¿Podrías tambien especificar un poco las decisiones técnicas a la hora de crear la entidad? Propiedades y formas de almacenarlas, métodos en el caso de necesitar, etc.

**Comment by argelion14** [comment]
Al desarrollar el objeto valor cita he decidido almacenar el identificador en una cadena, para que pueda tomar valores de código de país, así como otro objeto valor cita ya sea lo mencionado en el issue #17, #18 o #19 que se crea a partir del nombre que recibe el contructor

**Comment by Antobio17** [comment]
> Al desarrollar el objeto valor cita he decidido almacenar el identificador en una cadena, para que pueda tomar valores de código de país, así como otro objeto valor cita ya sea lo mencionado en el issue #17, #18 o #19 que se crea a partir del nombre que recibe el contructor

¿A que te refieres con el código de país para el identificador del cliente?
¿El otro objeto valor al que haces referencia es un tipo de cita no una cita entiendo verdad? No tendría sentido almacenar una cita en una cita.

**Comment by argelion14** [comment]
> > Al desarrollar el objeto valor cita he decidido almacenar el identificador en una cadena, para que pueda tomar valores de código de país, así como otro objeto valor cita ya sea lo mencionado en el issue #17, #18 o #19 que se crea a partir del nombre que recibe el contructor
> 
> ¿A que te refieres con el código de país para el identificador del cliente? ¿El otro objeto valor al que haces referencia es un tipo de cita no una cita entiendo verdad? No tendría sentido almacenar una cita en una cita.

Con el código de país me refiero a que se puede poner el +34 identificando de donde procede

**Comment by Antobio17** [comment]
> > > Al desarrollar el objeto valor cita he decidido almacenar el identificador en una cadena, para que pueda tomar valores de código de país, así como otro objeto valor cita ya sea lo mencionado en el issue #17, #18 o #19 que se crea a partir del nombre que recibe el contructor
> > 
> > 
> > ¿A que te refieres con el código de país para el identificador del cliente? ¿El otro objeto valor al que haces referencia es un tipo de cita no una cita entiendo verdad? No tendría sentido almacenar una cita en una cita.
> 
> Con el código de país me refiero a que se puede poner el +34 identificando de donde procede
> 
> El objeto valor que me refiero, son varios objeto valor que he creado para poder identificar los diferentes tipos que puede tener un cita

De acuerdo, sobreentiendo entonces que el identificador del usuario será el número de teléfono, para que quede reflejado ya que no se había mencionado en el comentario.

**Comment by argelion14** [comment]
> En relación al issue #7 voy a abordar el problema desarrollando el objeto valor cita que almacenará los tipos de cita deseados así como un identificador del cliente

un identificador del cliente que será un número de teléfono

**Comment by Antobio17** [comment]
:100:
