### ISSUE TITLE
Peinado para bodas como objeto valor

### ISSUE THREAD

**Issue by argelion14** [Antobio17/IV#19]
En relación al issue #7 he decido realizar una manera de almacenar el peinado para bodas, que apoye al issue #16 mediante un objeto valor que almacenar los datos necesarios que se hacen referencia en [tipo de cita](https://github.com/Antobio17/IV/blob/master/docs/tipos_cita.md)

**Comment by Antobio17** [comment]
Me parece acertado 👍 pero, ¿podrías especificar la forma de almacenar los datos en **este y anteriores** objetos valor?

**Comment by argelion14** [comment]
Si los datos se almacenarán mediante un string que recogerá el nombre del tipo que es, así como una estructura de diccionario para recoger los datos de tiempo que se mencionan en [tipo de cita](https://github.com/Antobio17/IV/blob/master/docs/tipos_cita.md)
