### ISSUE TITLE
Entidad citas

### ISSUE THREAD

**Issue by argelion14** [Antobio17/IV#20]
Voy a proceder a abordar la implementación de lo que se describe en el issue #7 con un entidad citas que recoja un conjunto de citas, las cuales se podrán modificar y añadir a la lista, estas citas contarán con un atributo que nos diga la hora, otro para el turno y finalmente el objeto valor mencionado en el issue #16

**Comment by Antobio17** [comment]
Las citas no deberían poder modificarse, no se especifica en la HU1 #7.
Tampoco se indica que se almacene la hora, debería almacenar el día y el turno unicamente ya que en la futura lógica de negocio a implementar se organizarán los horarios de estas citas.

¿Podrías ilustrar un poco como será la estructura básica de la entidad? Creo que quedará bastante más claro.

**Comment by argelion14** [comment]
> Voy a proceder a abordar la implementación de lo que se describe en el issue #7 con un entidad citas que recoja un conjunto de citas, las cuales se podrán añadir a la lista, estas citas contarán con un atributo que nos diga la hora, otro para el turno y finalmente el objeto valor mencionado en el issue #16

La estructura que seguiría seria la siguiente:

      citas = {
      "fecha" :  "datetime de python",
      "turno" : "mañana",
      "cita" : "objetoValorCita"
      }

**Comment by Antobio17** [comment]
Creo que entiendo el pensamiento de estructuración pero no está bien representado:

- Al almacenar tener la clave de diccionario fecha, turno, y cita no habría de almacenar varias citas, es decir en ese trozo de código _citas_ guarda una única cita. Sería mas apropiado almacenar las distintas fechas como key principal y dentro contendrán los turnos correspondientes que a su vez tendrán las citas asociadas a esos turnos.
- El campo fecha se debería almacenar como un string del dia/mes/año ya el objeto _datetime_ contiene además del día la hora (la cual no se decidirá en el momento de la reserva)

De todas formas esta implementación será para la parte de lógica de negocio y bien es cierto que en la entidad citas la propiedad solo se deberá inicializar con un diccionario vacío.

**Comment by argelion14** [comment]
> Voy a proceder a abordar la implementación de lo que se describe en el issue #7 con un entidad citas que recoja un conjunto de citas, las cuales se podrán añadir a la lista, estas citas contarán con un atributo que nos diga la hora, otro para el turno y finalmente el objeto valor mencionado en el issue #16
> 
> La estructura que seguiría seria la siguiente:
> 
> ```
>   citas = {
>   }
> ```

No se implementará la estructura, al igual que no se implementará el método que añada citas compuestas de fecha, turno y cita, solo se añadirá el mismo

**Comment by Antobio17** [comment]
:+1:
