### ISSUE TITLE
Tipo de error para fallo en teléfono

### ISSUE THREAD

**Issue by argelion14** [Antobio17/IV#22]
Se desarrolla una excepción que apoye al issue #16 denominada PhoneFormatError que saltará cuando el teléfono introducido no sea una cadena

**Comment by JJ** [comment]
Sigue siendo una descripción de lo que vas a  hacer, y no de un problema. ¿De veras es tan difícil escribir algo así?

> El formato del teléfono que se admite es x. Puede fallar de varias formas: x, y y z. El programador necesitará saber de qué forma ha fallado y qué necesita para corregir el fallo.
